### ISSUE TITLE
Generate links for all headers

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/grunt-jquery-content#36]
All content should have linkable headers. We already have code for this with the TOC option, but we should pull out the linking code and have it always run.

There should be an option for generating the TOC or generating a sidebar TOC, like the QUnit pages (separate feature).

We should use `name` instead of `id` so sub-headers that are duplicated across posts won't generate invalid HTML on listing pages.

We should try to support HTML in addition to markdown.

**Comment by Krinkle** [comment]
Closing in favour of continued/slow adoption of Markdown.
