### ISSUE TITLE
Generate id-attributes for properties

### ISSUE THREAD

**Issue by jzaefferer** [jquery/grunt-jquery-content#39]
Affects for example http://api.qunitjs.com/QUnit.config/

Even though there's no ToC here, it would still be useful to have id-attributes on each property to create manual deeplinks.

I could make use of that for the non-widget options listing here: http://jqueryvalidation.org/validate/

**Comment by Krinkle** [comment]
Declining for now. The case of QUnit.config was addressed by moving each property to its own page with its own URL.
