### ISSUE TITLE
Ability to setup redirects

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/grunt-jquery-content#61]
Either as a per-post config in the post metadata or as a per-site config in the root of the repo.

**Comment by arthurvr** [comment]
I'm :+1: on a per-site config.

If we want to remove a page from a specific site now and setup redirects, what's the best way to handle that?

**Comment by gnarf** [comment]
'Right now' we need to add am nginx redirect rule in our puppet config. I
can show you the way.  Or just request @jquery/infrastructure to set them
up when you need them.

**Comment by gnarf** [comment]
Can anyone own this / get it done? I'd really like to not have to add redirects for everything to our puppet/nginx configs.

**Comment by gnarf** [comment]
I'm hoping that this would populate a list of redirects / alternates in the wordpress databases/plugins somewhere.  Whatever format works best.

**Comment by gnarf** [comment]
https://github.com/jquery/grunt-jquery-content/pull/69
https://github.com/jquery/jquery-wp-content/pull/368

**Comment by gnarf** [comment]
v2.3.0 of grunt-jquery-content adds the redirect.json via #69
